branches:
  only:
    - master

environment:
  matrix:
    - nodejs_version: ""
    - nodejs_version: "8"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node -v
  - npm -v
  - npm test

build: off
